export type Tag = {
  [key: string]: string;
};

export const tags: Tag = {
  '1': '$',
  '2': '$$',
  '3': '$$$',
  'breakfast_&_brunch': 'breakfast & brunch',
  street_food: 'street food',
  fast_casual: 'fast casual',
  diner: 'diner',
  family_style: 'family-style',
  casual_dining: 'casual dining',
  fine_dining: 'fine dining',
  buffet: 'buffet',
  gastropub: 'gastropub',
  gastrobar: 'gastrobar',
  tapas: 'tapas',
  burger: 'burger',
  pizza: 'pizza',
  italian: 'italian',
  asian: 'asian',
  vegetarian: 'vegetarian',
  vegan: 'vegan',
  hungarian: 'hungarian',
  turkish: 'turkish',
  mexican: 'mexican',
  indian: 'indian',
  jewish: 'jewish',
  kosher: 'kosher',
  halal: 'halal',
  steak: 'steak',
  salad: 'salad',
  soup: 'soup',
  greek: 'greek',
  'gyros_&_kebab': 'gyros & kebab',
  thai: 'thai',
  'sandwich_&_bagel': 'sandwich & bagel',
  japanese: 'japanese',
  chinese: 'chinese',
  fish: 'fish',
  gluten_free: 'gluten-free',
  vietnamese: 'vietnamese',
  israeli: 'israeli',
  american: 'american',
  hummus: 'hummus',
  french: 'french',
  korean: 'korean',
  russian: 'russian',
  ukrainian: 'ukrainian',
  crepe: 'crepe',
  african: 'african',
  georgian: 'georgian',
  balkan: 'balkan',
  latin_american: 'latin american',
  fusion: 'fusion',
  middle_eastern: 'middle eastern',
  'patisserie_&_bakery': 'patisserie & bakery',
  chocolaterie: 'chocolaterie',
  ice_cream: 'ice cream',
  waffles: 'waffles',
  churros: 'churros',
  cafe: 'cafe',
  tea: 'tea',
  smoothies: 'smoothies',
  park: 'park',
  tourist_attraction: 'tourist attraction',
  adventure_park: 'adventure park',
  zoo: 'zoo',
  water_park: 'water park',
  spa: 'spa',
  massage: 'massage',
  art_gallery: 'art gallery',
  museum: 'museum',
  theatre: 'theatre',
  movie_theatre: 'movie theatre',
  open_air_screening: 'open air screening',
  adventure: 'adventure',
  escape_room: 'escape room',
  go_kart: 'go-kart',
  shooting_range: 'shooting range',
  paintball: 'paintball',
  laser_tag: 'laser tag',
  virtual_reality: 'virtual reality',
  bar: 'bar',
  wine_bar: 'wine bar',
  cocktail_lounge: 'cocktail lounge',
  sports_bar: 'sports bar',
  karaoke_bar: 'karaoke bar',
  live_music: 'live music',
  festival: 'festival',
  pub: 'pub',
  dance_club: 'dance club',
  social_dance_lounge: 'social-dance lounge',
  electronic: 'electronic',
  pop: 'pop',
  hip_hop: 'hip-hop',
  blues: 'blues',
  classical: 'classical',
  country: 'country',
  folk: 'folk',
  funk: 'funk',
  indie_alternative: 'indie/alternative',
  retro: 'retro',
  jam: 'jam',
  jazz: 'jazz',
  metal: 'metal',
  punk: 'punk',
  rock: 'rock',
  soul: 'soul',
  'balkan_&_gypsy': 'balkan & gypsy',
  karaoke: 'karaoke',
  concerts: 'concerts',
  scenic: 'scenic',
  cult: 'cult',
  open_air: 'open-air',
  semi_open_air: 'semi open-air',
  skybar: 'skybar',
  ruin_bar: 'ruin bar',
  industrial: 'industrial',
  trendy: 'trendy',
  premium: 'premium',
  high_demand: 'high-demand',
  dress_code: 'dress code',
  over_25: 'over 25',
  iconic: 'iconic',
  coworking: 'coworking',
  kiosk: 'kiosk',
  mini: 'tiny',
  intimate: 'small',
  spacious: 'spacious',
  multi_venue: 'multi-venue',
  hall: 'hall',
  frivolous_crowd: 'frivolous crowd',
  casual_crowd: 'casual crowd',
  mainstream_crowd: 'mainstream crowd',
  chic_crowd: 'chic crowd',
  upscale_crowd: 'upscale crowd',
  high_end_crowd: 'high-end crowd',
  lgbtq: 'lgbtq',
  lgbtq_friendly: 'lgbtq friendly',
  mostly_tourists: 'mostly tourists',
  mostly_expats: 'mostly expats',
  mostly_locals: 'mostly locals',
  locals_and_expats: 'locals and expats',
  locals_and_tourists: 'locals and tourists',
  expats_and_tourists: 'expats and tourists',
  teens: 'teens',
  students: 'students',
  young_adults: 'young adults',
  adults: 'adults',
  seniors: 'seniors',
  exhibition: 'exhibition',
  play: 'play',
  sport: 'sport',
  concert: 'concert',
  market: 'market',
  show: 'show',
  lecture: 'lecture',
  stand_up_comedy: 'stand-up comedy',
  dance: 'dance',
  opening: 'opening',
  screening: 'screening',
  parade: 'parade',
  rally: 'rally',
  debate: 'debate',
  workshop: 'workshop',
  religious: 'religious',
  children: 'children',
  supermarket: 'supermarket',
  food: 'food',
  book: 'book',
  jewelry: 'jewelry',
  fashion: 'fashion',
  electronics: 'electronics',
  art: 'art',
  toys: 'toys',
  beauty: 'beauty',
  health: 'health',
  pharmacy: 'pharmacy',
  drug_store: 'drug store',
  second_hand_books: 'second hand books',
  thrift_store: 'thrift store',
  souvenir: 'souvenir',
  gift: 'gift',
  baby: 'baby',
  pet_store: 'pet store',
  convenience_store: 'convenience store',
  furniture: 'furniture',
  florist: 'florist',
  watch: 'watch',
  shoe: 'shoe',
  kids: 'kids',
  home: 'home',
  accessories: 'accessories',
  lifestyle: 'lifestyle',
  novelty: 'novelty',
  artisan: 'artisan',
  local: 'local',
  ceramics: 'ceramics',
  perfume: 'perfume',
  contemporary: 'contemporary',
  beer_bar: 'beer bar',
  budget_bar: 'budget bar',
  european: 'european',
  ramen: 'ramen',
  pho: 'pho',
  healthy: 'healthy',
  deli: 'deli',
  cozy: 'cozy',
  thematic: 'thematic',
  no_frills: 'no-frills',
  atmospheric: 'atmospheric',
  gastronome: 'gastronome',
  pet_friendly: 'pet-friendly',
  novel: 'novel',
  unusual: 'unusual',
  lunch_menu: 'lunch menu',
  eatery: 'eatery',
  fine_bistro: 'fine bistro',
  maccaron: 'maccaron',
  sushi: 'sushi',
  bubble_tea: 'bubble tea',
  hookah_shisha: 'hookah-shisha',
  basement: 'basement',
  tobacco_shop: 'tobacco shop',
  beverage: 'beverage',
  families: 'families',
  bowling: 'bowling',
  games_bar: 'games bar',
  arcades: 'arcades',
  billiard: 'billiard',
  darts: 'darts',
  board_games: 'board games',
  pub_games: 'pub games',
  extreme_experience: 'extreme experience',
  experience_park: 'experience park',
  vibrant: 'vibrant',
  buzzing: 'buzzing',
  relaxed: 'relaxed',
  tranquil: 'tranquil',
  mcdonalds: 'mcdonalds',
  burgerking: 'burgerking',
  zingbuger: 'zingburger',
  pizzame: 'pizzame',
  subway: 'subway',
  kfc: 'kfc',
  madalcafe: 'madalcafe',
  dm: 'dm',
  rossmann: 'rossmann',
  starbucks: 'starbucks',
  hm: 'h&m',
  zara: 'zara',
  lush: 'lush',
  thebodyshop: 'thebodyshop',
  decathlon: 'decathlon',
  officeshoes: 'officeshoes',
  playersroom: 'playersroom',
  bambamarha: 'bambamarha',
  douglas: 'douglas',
  emag: 'emag',
  pizzahut: 'pizzahut',
  vodafone: 'vodafone',
  telekom: 'telekom',
  yettel: 'yettel',
  libri: 'libri',
  aldi: 'aldi',
  spar: 'spar',
  lidl: 'lidl',
  cba: 'cba',
  roniabc: 'roniabc',
  hervis: 'hervis',
  adidas: 'adidas',
  nike: 'nike',
  'c&a': 'c&a',
  porkolt: 'porkolt',
  langos: 'langos',
  chimney_cake: 'chimney cake',
  goulash: 'goulash',
  hungarian_fish_soup: 'hungarian fish soup',
  cholent: 'cholent',
  hungarian_bean_soup: 'hungarian bean soup',
  gym: 'gym',
  tennis: 'tennis',
  yoga: 'yoga',
  swimming_pool: 'swimming pool',
  squash: 'squash',
  basketball: 'basketball',
  aerobics: 'aerobics',
  pilates: 'pilates',
  spinning: 'spinning',
  bjj: 'bjj',
  boxing: 'boxing',
  karate: 'karate',
  judo: 'judo',
  thaibox: 'thaibox',
  k1: 'k1',
  martial_arts: 'martial arts',
  kung_fu: 'kung fu',
  krav_maga: 'krav maga',
  wrestling: 'wrestling',
  kickbox: 'kickbox',
  mma: 'mma',
  crossfit: 'crossfit',
  horseback_riding: 'horseback riding',
  beach: 'beach',
  boat_rental: 'boat rental',
  jetski_rental: 'jetski rental',
  sup_rental: 'sup rental',
  fishing: 'fishing',
  water_skiing: 'water skiing',
  wake_boarding: 'wake boarding',
  rafting: 'rafting',
  skiing: 'skiing',
  sailing: 'sailing',
  surfing: 'surfing',
  kitesurfing: 'kitesurfing',
  scuba_diving: 'scuba diving',
  library: 'library',
  autumn_locations: 'Most atmospheric autumn locations',
  winter_brunch: 'Winter brunch',
  trending_on_shorty: 'Trending on Shorty',
  shortlist_1: 'Mulled wine season',
  shortlist_2: 'One weekend in the city',
  shortlist_3: 'One day int he city',
  shortlist_5: 'Nearby gems',
  shortlist_6: 'Top 10 best Goulash in Budapest',
  shortlist_7: 'Artisan beer bars',
  shortlist_8: 'Top holiday markets',
  shortlist_9: 'Hello Winter - téli élmények',
  shortlist_10: 'Book a table',
  shortlist_11: 'Yiddishe momme',
  shortlist_12: 'Best Asian restaurants in Budapest',
  shortlist_13: 'Detox after Christmas',
  shortlist_14: 'The Best cafés in Budapest for getting work done',
  shortlist_15: 'Popular brunch spots in Budapest',
  shortlist_16: 'Serene oasis dining spots in Budapest',
  shortlist_17: 'Top 3 most visited vegan spots',
  shortlist_18: 'A Weekend in Budapest',
  shortlist_19: 'Soup season',
  shortlist_20: 'Popular hungarian restaurants in Budapest',
  shortlist_21: 'Lunar New Year selection',
  shortlist_22: 'Sharing = Tapas',
  shortlist_23: 'Placeholder',
  shortlist_24: 'Placeholder',
  shortlist_25: 'Placeholder',
  shortlist_26: 'Placeholder',
};
